# Generated by Django 6.0.1 on 2026-01-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('raqam', models.IntegerField(max_length=50)),
                ('year', models.DateField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
